services:
  payment-postgres:
    image: postgres:16-alpine
    container_name: payment-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_PAYMENT}
    ports:
      - "5432:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data

  wallet-postgres:
    image: postgres:16-alpine
    container_name: wallet-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_WALLET}
    ports:
      - "5433:5432"
    volumes:
      - wallet_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: payment-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

volumes:
  payment_postgres_data:
  wallet_postgres_data: