services:
  payment-postgres:
    image: postgres:16-alpine
    container_name: payment-postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=payment_db
    ports:
      - "5432:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data

  wallet-postgres:
    image: postgres:16-alpine
    container_name: wallet-postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=wallet_db
    ports:
      - "5433:5432"
    volumes:
      - wallet_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: payment-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  payment_postgres_data:
  wallet_postgres_data: